
package restaurantqueuing;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        setTitle("Restaurant Queuing");
        initComponents();
        setPropertiesMenuTables();
        currentTime();
        setLocationRelativeTo(null);
        queue = new Queuing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuBar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlTableMenu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBeverageMenu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFoodMenu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalFoodPrice = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalBeveragePrice = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCheck = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblTableNo = new javax.swing.JLabel();
        lblReserve = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSnacks = new javax.swing.JButton();
        btnFoods = new javax.swing.JButton();
        btnBeverages = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlMenuButton = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMenuBar.setPreferredSize(new java.awt.Dimension(800, 70));

        jButton1.setText("RESERVE");

        jButton2.setText("REVENUE");
        jButton2.setPreferredSize(new java.awt.Dimension(85, 25));

        javax.swing.GroupLayout pnlMenuBarLayout = new javax.swing.GroupLayout(pnlMenuBar);
        pnlMenuBar.setLayout(pnlMenuBarLayout);
        pnlMenuBarLayout.setHorizontalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuBarLayout.setVerticalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlContent.setPreferredSize(new java.awt.Dimension(0, 500));

        pnlTableMenu.setBackground(new java.awt.Color(204, 204, 204));
        pnlTableMenu.setPreferredSize(new java.awt.Dimension(415, 460));

        tblBeverageMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Beverages", "Price", "Qty.", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBeverageMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBeverageMenuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBeverageMenu);

        tblFoodMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Foods", "Price", "Qty.", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFoodMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFoodMenuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblFoodMenu);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalFoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTotalFoodPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalBeveragePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTotalBeveragePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlTableMenuLayout = new javax.swing.GroupLayout(pnlTableMenu);
        pnlTableMenu.setLayout(pnlTableMenuLayout);
        pnlTableMenuLayout.setHorizontalGroup(
            pnlTableMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTableMenuLayout.setVerticalGroup(
            pnlTableMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableMenuLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCheck.setText("Check Tables");
        btnCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Table No.  :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Reserve    :");

        lblTableNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblReserve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblReserve, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(lblTableNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTableNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(lblDate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(lblTime)))
                        .addGap(3, 3, 3))
                    .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        btnSnacks.setText("Snacks");
        btnSnacks.setPreferredSize(new java.awt.Dimension(90, 25));
        btnSnacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSnacksMouseClicked(evt);
            }
        });

        btnFoods.setText("Foods");
        btnFoods.setPreferredSize(new java.awt.Dimension(90, 25));
        btnFoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoodsMouseClicked(evt);
            }
        });

        btnBeverages.setText("Beverages");
        btnBeverages.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFoods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBeverages)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBeverages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout pnlMenuButtonLayout = new javax.swing.GroupLayout(pnlMenuButton);
        pnlMenuButton.setLayout(pnlMenuButtonLayout);
        pnlMenuButtonLayout.setHorizontalGroup(
            pnlMenuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMenuButtonLayout.setVerticalGroup(
            pnlMenuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlMenuButton);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("TOTAL");

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalPrice.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblTotalPrice)
        );

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnDone.setBackground(new java.awt.Color(51, 204, 0));
        btnDone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDone.setText("DONE");
        btnDone.setPreferredSize(new java.awt.Dimension(85, 31));
        btnDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnClear)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDone, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlTableMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlTableMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chew ID : ");

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSnacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSnacksMouseClicked
        if(clickMenuButton) pnlMenuButton.removeAll();
        addSnacksButton();
        clickMenuButton = true;
    }//GEN-LAST:event_btnSnacksMouseClicked

    private void btnBeveragesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseClicked
        if(clickMenuButton) pnlMenuButton.removeAll();
        addBevaragesButton();
        clickMenuButton = true;
    }//GEN-LAST:event_btnBeveragesMouseClicked

    private void btnFoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodsMouseClicked
        if(clickMenuButton) pnlMenuButton.removeAll();
        addFoodsButton();
        clickMenuButton = true;
    }//GEN-LAST:event_btnFoodsMouseClicked

    private void tblFoodMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFoodMenuMouseClicked
        if(evt.getClickCount() == 2) {
            int row = tblFoodMenu.getSelectedRow();
            int res = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure you want to delete row " + (tblFoodMenu.getSelectedRow() + 1) + " ?", "Please Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
            switch (res) {
                
                case javax.swing.JOptionPane.YES_OPTION :
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblFoodMenu.getModel();

                    computePrice(lblTotalFoodPrice, removeComma(String.valueOf(model.getValueAt(row, 4))), "-");
                    computePrice(lblTotalPrice, removeComma(String.valueOf(model.getValueAt(row, 4))), "-");
                    
                    model.removeRow(row);
                    tblFoodMenuLine--;

                    for(int i = row; i < tblFoodMenuLine; i++) {
                        model.setValueAt(i+1, i, 0);
                    }
                    
                    javax.swing.JOptionPane.showMessageDialog(null, "Delete Successfully");
                    break;
                    
                case javax.swing.JOptionPane.NO_OPTION :
                    javax.swing.JOptionPane.showMessageDialog(null, "Delete Action is Canceled");
                    break;
            }   
        }
    }//GEN-LAST:event_tblFoodMenuMouseClicked

    private void tblBeverageMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBeverageMenuMouseClicked
        if(evt.getClickCount() == 2) {
            int row = tblBeverageMenu.getSelectedRow();
            int res = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure you want to delete row " + (tblBeverageMenu.getSelectedRow() + 1) + " ?", "Please Cofirm", javax.swing.JOptionPane.YES_NO_OPTION);
            switch (res) {
                
                case javax.swing.JOptionPane.YES_OPTION :
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBeverageMenu.getModel();
                    
                    computePrice(lblTotalBeveragePrice, removeComma(String.valueOf(model.getValueAt(row, 4))), "-");
                    computePrice(lblTotalPrice, removeComma(String.valueOf(model.getValueAt(row, 4))), "-");
                    
                    model.removeRow(row);
                    tblBeverageMenuLine--;
                    
                    for(int i = row; i < tblBeverageMenuLine; i++) {
                        model.setValueAt(i+1, i, 0);
                    }
                    
                    javax.swing.JOptionPane.showMessageDialog(null, "Delete Successfully");
                    break;
                    
                case javax.swing.JOptionPane.NO_OPTION :
                    javax.swing.JOptionPane.showMessageDialog(null, "Delete Action is Canceled");
                    break;
            }   
        }
    }//GEN-LAST:event_tblBeverageMenuMouseClicked

    private void btnCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckMouseClicked
        new CheckAvailable().setVisible(true);
    }//GEN-LAST:event_btnCheckMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Queuing.disConnectDb();
    }//GEN-LAST:event_formWindowClosing

    private void btnDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoneMouseClicked
        if(lblTableNo.getText().equals("") || lblReserve.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select table No. and time reserve");
        } else if(txtName.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please input customer's name");
        } else if(tblFoodMenuLine == 0 && tblBeverageMenuLine == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select orders");
        } else {
            customerId = queue.checkName(txtName.getText());
            setOrders(tblFoodMenuLine, tblFoodMenu);
            setOrders(tblBeverageMenuLine, tblBeverageMenu);
            queue.updateStatusTable(tableId);
            resetToDefault();
            javax.swing.JOptionPane.showMessageDialog(null, "Successfully");
        }
    }//GEN-LAST:event_btnDoneMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        resetToDefault();
    }//GEN-LAST:event_btnClearMouseClicked

    private void resetToDefault() {
        tableId = customerId = -1;
        tblFoodMenuLine = tblBeverageMenuLine = 0;
        dateTimeReserve = timeOut = null;
        lblTableNo.setText("");
        lblReserve.setText("");
        txtName.setText("");
        deleteAllRow((javax.swing.table.DefaultTableModel) tblFoodMenu.getModel());
        deleteAllRow((javax.swing.table.DefaultTableModel) tblBeverageMenu.getModel());
    }
    
    private void deleteAllRow(javax.swing.table.DefaultTableModel model) {
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
    }
    
    private void setOrders(int line, javax.swing.JTable tbl) {
        for(int i = 0; i < line; i++) {
            String foodName = String.valueOf(tbl.getValueAt(i, 1));
            int qty = Integer.parseInt(String.valueOf(tbl.getValueAt(i, 3)));
            String reserve = dateTimeReserve.toString().substring(0, dateTimeReserve.toString().length()-2);
            String out = timeOut.toString().substring(0, timeOut.toString().length()-2);
            queue.insertOrders(reserve , out, queue.checkFood(foodName), qty, tableId, customerId);
        }
    }
    
    private void currentTime() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               java.text.DateFormat timeFormat = new java.text.SimpleDateFormat("dd-MM-yyyy   HH:mm:ss");
               java.util.Calendar currentTime = new java.util.GregorianCalendar();
               currentTime.add(java.util.Calendar.YEAR, -543);
               lblClock.setText(timeFormat.format(currentTime.getTime()));

               java.text.DateFormat currentFormat = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
               queue.removeOrders(currentFormat.format(currentTime.getTime()));
           } 
        });
        timer.start();
        
    }
    
    private void setPropertiesMenuTables() {
        tblFoodMenu.getColumnModel().getColumn(0).setPreferredWidth(15);
        tblFoodMenu.getColumnModel().getColumn(1).setPreferredWidth(210);
        tblFoodMenu.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblFoodMenu.getColumnModel().getColumn(3).setPreferredWidth(15);
        tblFoodMenu.getColumnModel().getColumn(4).setPreferredWidth(60);

        tblBeverageMenu.getColumnModel().getColumn(0).setPreferredWidth(15);
        tblBeverageMenu.getColumnModel().getColumn(1).setPreferredWidth(210);
        tblBeverageMenu.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblBeverageMenu.getColumnModel().getColumn(3).setPreferredWidth(15);
        tblBeverageMenu.getColumnModel().getColumn(4).setPreferredWidth(60);
        
        javax.swing.table.DefaultTableCellRenderer leftRenderer = new javax.swing.table.DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        for(int i = 0; i <= 4; i++) {
            tblFoodMenu.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
            tblBeverageMenu.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }
        
        javax.swing.table.DefaultTableCellRenderer centerRendererFood = (javax.swing.table.DefaultTableCellRenderer)tblFoodMenu.getTableHeader().getDefaultRenderer();
        centerRendererFood.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        javax.swing.table.DefaultTableCellRenderer centerRendererBeverage = (javax.swing.table.DefaultTableCellRenderer)tblBeverageMenu.getTableHeader().getDefaultRenderer();
        centerRendererBeverage.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }
    
    private void addtblFoodMenuLine(javax.swing.JButton btn, double price) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblFoodMenu.getModel();
        int i = 0;
        
        for(i = 0; i < tblFoodMenuLine; i++) {
            if(btn.getText().equals(model.getValueAt(i, 1))) {
                model.setValueAt((int)(model.getValueAt(i, 3))+1, i, 3);
                model.setValueAt(putComma(price*removeComma(String.valueOf(model.getValueAt(i, 3)))), i, 4);
                break;
            }
        }
        
        if(tblFoodMenuLine == 0 || i >= tblFoodMenuLine) {
            model.addRow(new Object[0]);
            tblFoodMenu.setValueAt(tblFoodMenuLine + 1, tblFoodMenuLine, 0);
            tblFoodMenu.setValueAt(btn.getText(), tblFoodMenuLine, 1);
            tblFoodMenu.setValueAt(price + "0.-", tblFoodMenuLine, 2);
            tblFoodMenu.setValueAt(1, tblFoodMenuLine, 3);
            tblFoodMenu.setValueAt(price + "0.-", tblFoodMenuLine, 4);
            tblFoodMenuLine++;
        }
        
        computePrice(lblTotalFoodPrice, price, "+");
        computePrice(lblTotalPrice, price, "+");
    }
    
    private void addtblBeverageMenuLine(javax.swing.JButton btn, double price) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBeverageMenu.getModel();
        int i = 0;

        for(i = 0; i < tblBeverageMenuLine; i++) {
            if(btn.getText().equals(model.getValueAt(i, 1))) {
                model.setValueAt((int)(model.getValueAt(i, 3))+1, i, 3);
                model.setValueAt(putComma(price*removeComma(String.valueOf(model.getValueAt(i, 3)))), i, 4);
                break;
            }
        }
        
        if(tblBeverageMenuLine == 0 || i >= tblBeverageMenuLine) {
            model.addRow(new Object[0]);
            tblBeverageMenu.setValueAt(tblBeverageMenuLine + 1, tblBeverageMenuLine, 0);
            tblBeverageMenu.setValueAt(btn.getText(), tblBeverageMenuLine, 1);
            tblBeverageMenu.setValueAt(price + "0.-", tblBeverageMenuLine, 2);
            tblBeverageMenu.setValueAt(1, tblBeverageMenuLine, 3);
            tblBeverageMenu.setValueAt(price + "0.-", tblBeverageMenuLine, 4);
            tblBeverageMenuLine++;
        }

        computePrice(lblTotalBeveragePrice, price, "+");
        computePrice(lblTotalPrice, price, "+");
    }
    
    private void addSnacksButton() {
        btnFriedFishPasteBalls = new javax.swing.JButton();
        btnCharcoalBoiledPorkNeck = new javax.swing.JButton();
        btnFriedChicken = new javax.swing.JButton();
        btnFriedPorkRind = new javax.swing.JButton();
        btnCrispyWonton = new javax.swing.JButton();
        btnSteamedSpringRoll = new javax.swing.JButton();

        btnFriedFishPasteBalls.setText("Fried Fish-Paste Balls");
        btnFriedFishPasteBalls.setPreferredSize(new java.awt.Dimension(170, 50));
        btnFriedFishPasteBalls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
		addtblFoodMenuLine(btnFriedFishPasteBalls, 85.0);
            }
        });

        btnCharcoalBoiledPorkNeck.setText("Charcoal-Boiled Pork Neck");
        btnCharcoalBoiledPorkNeck.setPreferredSize(new java.awt.Dimension(170, 50));
        btnCharcoalBoiledPorkNeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnCharcoalBoiledPorkNeck, 110.0);
            }
        });

        btnFriedChicken.setText("Fried Chicken");
        btnFriedChicken.setPreferredSize(new java.awt.Dimension(170, 50));
        btnFriedChicken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnFriedChicken, 60.0);
            }
        });

        btnFriedPorkRind.setText("Fried Pork Rind");
        btnFriedPorkRind.setPreferredSize(new java.awt.Dimension(170, 50));
        btnFriedPorkRind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnFriedPorkRind, 70.0);
            }
        });

        btnCrispyWonton.setText("Crispy Wonton");
        btnCrispyWonton.setPreferredSize(new java.awt.Dimension(170, 50));
        btnCrispyWonton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnCrispyWonton, 60.0);
            }
        });

        btnSteamedSpringRoll.setText("Steamed Spring Roll");
        btnSteamedSpringRoll.setPreferredSize(new java.awt.Dimension(170, 50));
        btnSteamedSpringRoll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnSteamedSpringRoll, 60.0);
            }
        });

        javax.swing.GroupLayout pnlSnacksLayout = new javax.swing.GroupLayout(pnlMenuButton);
        pnlMenuButton.setLayout(pnlSnacksLayout);
        pnlSnacksLayout.setHorizontalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnFriedFishPasteBalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCharcoalBoiledPorkNeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnFriedChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFriedPorkRind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnCrispyWonton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSteamedSpringRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSnacksLayout.setVerticalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFriedFishPasteBalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharcoalBoiledPorkNeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFriedChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFriedPorkRind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrispyWonton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSteamedSpringRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    
    private void addFoodsButton() {
        btnRice = new javax.swing.JButton();
        btnCasseroledPrawns = new javax.swing.JButton();
        btnSteamedDuck = new javax.swing.JButton();
        btnFriedFishToppedWithChilliSauce = new javax.swing.JButton();
        btnSpicyVermicelliSalad = new javax.swing.JButton();
        btnChickenGreenCurry = new javax.swing.JButton();
        btnClearSoup = new javax.swing.JButton();
        btnMincedPorkOmelet = new javax.swing.JButton();
        btnFriedCrabinYellowCurry = new javax.swing.JButton();
        btnDeepFriendShrimpCakes = new javax.swing.JButton();
        btnTomYumKung = new javax.swing.JButton();
        
        btnRice.setText("Rice");
        btnRice.setPreferredSize(new java.awt.Dimension(170, 50));
        btnRice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnRice, 30.0);
            }
        });
        
        btnCasseroledPrawns.setText("Casseroled Prawns");
        btnCasseroledPrawns.setPreferredSize(new java.awt.Dimension(170, 50));
        btnCasseroledPrawns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnCasseroledPrawns, 120.0);
            }
        });
        
        btnSteamedDuck.setText("Steamed Duck");
        btnSteamedDuck.setPreferredSize(new java.awt.Dimension(170, 50));
        btnSteamedDuck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnSteamedDuck, 120.0);
            }
        });
        
        btnFriedFishToppedWithChilliSauce.setText("Fried Fish Topped With Chilli Sauce");
        btnFriedFishToppedWithChilliSauce.setPreferredSize(new java.awt.Dimension(170, 50));
        btnFriedFishToppedWithChilliSauce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnFriedFishToppedWithChilliSauce, 220.0);
            }
        });
        
        btnSpicyVermicelliSalad.setText("Spicy Vermicelli Salad");
        btnSpicyVermicelliSalad.setPreferredSize(new java.awt.Dimension(170, 50));
        btnSpicyVermicelliSalad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnSpicyVermicelliSalad, 120.0);
            }
        });
        
        btnChickenGreenCurry.setText("Chicken Green Curry");
        btnChickenGreenCurry.setPreferredSize(new java.awt.Dimension(170, 50));
        btnChickenGreenCurry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnChickenGreenCurry, 130.0);
            }
        });
        
        btnClearSoup.setText("Clear Soup");
        btnClearSoup.setPreferredSize(new java.awt.Dimension(170, 50));
        btnClearSoup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnClearSoup, 90.0);
            }
        });
        
        btnMincedPorkOmelet.setText("Minced Pork Omelet");
        btnMincedPorkOmelet.setPreferredSize(new java.awt.Dimension(170, 50));
        btnMincedPorkOmelet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnMincedPorkOmelet, 160.0);
            }
        });
        
        btnFriedCrabinYellowCurry.setText("Fried Crab in Yellow Curry");
        btnFriedCrabinYellowCurry.setPreferredSize(new java.awt.Dimension(170, 50));
        btnFriedCrabinYellowCurry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnFriedCrabinYellowCurry, 190.0);
            }
        });
        
        btnDeepFriendShrimpCakes.setText("Deep-Friend Shrimp Cakes");
        btnDeepFriendShrimpCakes.setPreferredSize(new java.awt.Dimension(170, 50));
        btnDeepFriendShrimpCakes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnDeepFriendShrimpCakes, 180.0);
            }
        });
        
        btnTomYumKung.setText("Tom Yum Kung");
        btnTomYumKung.setPreferredSize(new java.awt.Dimension(170, 50));
        btnTomYumKung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblFoodMenuLine(btnTomYumKung, 180.0);
            }
        });
        
        javax.swing.GroupLayout pnlSnacksLayout = new javax.swing.GroupLayout(pnlMenuButton);
        pnlMenuButton.setLayout(pnlSnacksLayout);
        pnlSnacksLayout.setHorizontalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCasseroledPrawns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnSteamedDuck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFriedFishToppedWithChilliSauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnSpicyVermicelliSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChickenGreenCurry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnClearSoup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMincedPorkOmelet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnFriedCrabinYellowCurry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeepFriendShrimpCakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnTomYumKung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSnacksLayout.setVerticalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCasseroledPrawns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSteamedDuck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFriedFishToppedWithChilliSauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSpicyVermicelliSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChickenGreenCurry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)) 
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearSoup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMincedPorkOmelet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFriedCrabinYellowCurry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeepFriendShrimpCakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTomYumKung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    
    private void addBevaragesButton() {   
        btnWater = new javax.swing.JButton();
        btnPepsi = new javax.swing.JButton();
        btnSprite = new javax.swing.JButton();
        btnFanta = new javax.swing.JButton();
        btnSoda = new javax.swing.JButton();
        btnGreenTea = new javax.swing.JButton();

        btnWater.setText("Water");
        btnWater.setPreferredSize(new java.awt.Dimension(170, 50));
        btnWater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblBeverageMenuLine(btnWater, 15.0);
            }
        });
        
        btnPepsi.setText("Pepsi");
        btnPepsi.setPreferredSize(new java.awt.Dimension(170, 50));
        btnPepsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblBeverageMenuLine(btnPepsi, 25.0);
            }
        });
        
        btnSprite.setText("Sprite");
        btnSprite.setPreferredSize(new java.awt.Dimension(170, 50));
        btnSprite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblBeverageMenuLine(btnSprite, 25.0);
            }
        });
        
        btnFanta.setText("Fanta");
        btnFanta.setPreferredSize(new java.awt.Dimension(170, 50));
        btnFanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblBeverageMenuLine(btnFanta, 25.0);
            }
        });
        
        btnSoda.setText("Soda");
        btnSoda.setPreferredSize(new java.awt.Dimension(170, 50));
        btnSoda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblBeverageMenuLine(btnSoda, 25.0);
            }
        });
        
        btnGreenTea.setText("Green Tea");
        btnGreenTea.setPreferredSize(new java.awt.Dimension(170, 50));
        btnGreenTea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtblBeverageMenuLine(btnGreenTea, 35.0);
            }
        });
        
        javax.swing.GroupLayout pnlSnacksLayout = new javax.swing.GroupLayout(pnlMenuButton);
        pnlMenuButton.setLayout(pnlSnacksLayout);
        pnlSnacksLayout.setHorizontalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSnacksLayout.createSequentialGroup()
                        .addComponent(btnSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGreenTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSnacksLayout.setVerticalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGreenTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    
    private void computePrice(javax.swing.JLabel label, double price, String sign) {
        double totalPrice = 0;
        if(label.getText().equals("")) totalPrice = price;
        else {
            switch(sign) {
                case "+" : totalPrice = removeComma(String.valueOf(label.getText())) + price;
                           break;
                case "-" : totalPrice = removeComma(String.valueOf(label.getText())) - price;  
            }
        }
        if(totalPrice == 0) label.setText("");
        else label.setText(putComma(totalPrice));
    }
    
    private int removeComma(String str) {
        int num = 0;
        try {
            java.text.NumberFormat format = java.text.NumberFormat.getInstance(java.util.Locale.getDefault());
            Number number = format.parse(str);
            num = number.intValue();
        } catch(java.text.ParseException e) {           
        }
        return num;
    }
    
    private String putComma(double num) {
    String s = String.valueOf(num);
    String res = "";
    if(s.length() <= 5) return s + "0.-";
    else {
      int cnt = 0;
      for(int i = s.length()-3; i >= 0; i--) {
        cnt++;
        res = s.charAt(i) + res;
        if(cnt == 3 && i > 0) {
          res = "," + res;
          cnt = 0;
        }
      }
      return res + ".00.-";
    }
  }
    
    public static Queuing getQueue() {
        return queue;
    }
    
    public static void setTableIdAndTime(int id, java.util.Calendar time) {
        tableId = id;      
        time.add(java.util.Calendar.YEAR, 543);
        dateTimeReserve = new java.sql.Timestamp(time.getTimeInMillis());
        time.add(java.util.Calendar.MINUTE, 90);
        timeOut = new java.sql.Timestamp(time.getTimeInMillis());
    }
    
    public static void setLabelDateAndTime(String tableNo, String time) {
        lblTableNo.setText("");
        lblReserve.setText("");

        lblTableNo.setText(tableNo);
        lblReserve.setText(time);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
   
    private static Queuing queue;

    private static int tableId;
    private static java.sql.Timestamp dateTimeReserve, timeOut;
    private int customerId;
    
    private boolean clickMenuButton;
    private int tblFoodMenuLine, tblBeverageMenuLine;

    // Snacks menu button
    private javax.swing.JButton btnFriedFishPasteBalls, btnCharcoalBoiledPorkNeck, btnFriedChicken,
                                btnFriedPorkRind, btnCrispyWonton, btnSteamedSpringRoll;

    // Foods menu button
    private javax.swing.JButton btnRice, btnCasseroledPrawns, btnSteamedDuck, btnFriedFishToppedWithChilliSauce,
                                btnSpicyVermicelliSalad, btnChickenGreenCurry, btnClearSoup, btnMincedPorkOmelet,
                                btnFriedCrabinYellowCurry, btnDeepFriendShrimpCakes, btnTomYumKung;
    
    // Beverages menu button
    private javax.swing.JButton btnWater, btnPepsi, btnSprite, btnFanta, btnSoda, btnGreenTea;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeverages;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnFoods;
    private javax.swing.JButton btnSnacks;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDate;
    private static javax.swing.JLabel lblReserve;
    private static javax.swing.JLabel lblTableNo;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotalBeveragePrice;
    private javax.swing.JLabel lblTotalFoodPrice;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMenuBar;
    private javax.swing.JPanel pnlMenuButton;
    private javax.swing.JPanel pnlTableMenu;
    private javax.swing.JTable tblBeverageMenu;
    private javax.swing.JTable tblFoodMenu;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}    

